import { StrictMode, useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

const API = import.meta.env.VITE_API_URL || 'http://localhost:4100/api';
async function api(path, options) { const response = await fetch(`${API}${path}`, { headers: { 'Content-Type': 'application/json', ...(options?.headers || {}) }, ...options }); const data = response.status === 204 ? null : await response.json(); if (!response.ok) throw new Error(data.error || 'Request failed'); return data; }
function base64ToUint8Array(value) { const normalized = `${value}${'='.repeat((4 - value.length % 4) % 4)}`.replace(/-/g, '+').replace(/_/g, '/'); return Uint8Array.from(atob(normalized), (character) => character.charCodeAt(0)); }
function App() {
  const [accounts, setAccounts] = useState([]); const [monitors, setMonitors] = useState([]); const [matches, setMatches] = useState([]); const [notice, setNotice] = useState(''); const [form, setForm] = useState({ emailAccountId: '', registrationNumber: '', pollIntervalSeconds: 60 });
  const refresh = async () => { try { const [a, m, r] = await Promise.all([api('/accounts'), api('/monitors'), api('/matches')]); setAccounts(a); setMonitors(m); setMatches(r); setForm((previous) => ({ ...previous, emailAccountId: previous.emailAccountId || a[0]?.id || '' })); } catch (error) { setNotice(error.message); } };
  useEffect(() => { refresh(); const timer = setInterval(refresh, 15000); return () => clearInterval(timer); }, []);
  const connect = (provider) => { window.location.assign(`${API}/auth/${provider}/start`); };
  const enablePush = async () => { try { if (!('serviceWorker' in navigator) || !('PushManager' in window)) throw new Error('This browser does not support web notifications.'); const config = await api('/push-config'); if (!config.publicKey) throw new Error('Web push is not configured on the server.'); const registration = await navigator.serviceWorker.register('/sw.js'); const subscription = await registration.pushManager.subscribe({ userVisibleOnly: true, applicationServerKey: base64ToUint8Array(config.publicKey) }); await api('/push-subscriptions', { method: 'POST', body: JSON.stringify(subscription) }); setNotice('Browser notifications are enabled.'); } catch (error) { setNotice(error.message); } };
  const createMonitor = async (event) => { event.preventDefault(); try { await api('/monitors', { method: 'POST', body: JSON.stringify(form) }); setNotice('Monitor created. The worker will scan it now.'); setForm((v) => ({ ...v, registrationNumber: '' })); refresh(); } catch (error) { setNotice(error.message); } };
  const action = async (id, endpoint) => { try { await api(`/monitors/${id}/${endpoint}`, { method: 'POST' }); setNotice(endpoint === 'scan' ? 'Scan queued.' : 'Monitor updated.'); refresh(); } catch (error) { setNotice(error.message); } };
  return <main><header><div><p className="eyebrow">INBOX INTELLIGENCE</p><h1>Registration Monitor</h1><p className="subtle">Find your identifier in email and supported documents before you miss an update.</p></div><div className="actions"><button className="quiet" onClick={enablePush}>Enable alerts</button><button className="quiet" onClick={refresh}>Refresh data</button></div></header>
    {notice && <p className="notice">{notice}</p>}
    <section className="connect"><div><p className="eyebrow">STEP 1</p><h2>Connect an authorized inbox</h2><p>Read-only OAuth. Tokens are encrypted before they reach PostgreSQL.</p></div><div className="buttons"><button onClick={() => connect('gmail')}>Connect Gmail</button><button className="outlook" onClick={() => connect('outlook')}>Connect Outlook</button></div></section>
    <section className="grid"><form className="card" onSubmit={createMonitor}><p className="eyebrow">STEP 2</p><h2>Create a monitor</h2><label>Authorized email account<select required value={form.emailAccountId} onChange={(e) => setForm({ ...form, emailAccountId: e.target.value })}><option value="">Select an account</option>{accounts.map((account) => <option key={account.id} value={account.id}>{account.provider} - {account.email_address}</option>)}</select></label><label>Registration number<input required placeholder="REG2026AIML00123" value={form.registrationNumber} onChange={(e) => setForm({ ...form, registrationNumber: e.target.value })}/></label><label>Scan interval (seconds)<input type="number" min="30" value={form.pollIntervalSeconds} onChange={(e) => setForm({ ...form, pollIntervalSeconds: Number(e.target.value) })}/></label><button disabled={!accounts.length}>Start monitoring</button></form>
      <div className="card"><p className="eyebrow">ACTIVE MONITORS</p><h2>Watchlist</h2>{monitors.length ? monitors.map((monitor) => <article className="monitor" key={monitor.id}><div><strong>{monitor.registration_number}</strong><span>{monitor.provider} · every {monitor.poll_interval_seconds}s</span>{monitor.last_error && <small className="error">{monitor.last_error}</small>}</div><div className="actions"><button className="small quiet" onClick={() => action(monitor.id, 'scan')}>Scan now</button><button className="small" onClick={() => action(monitor.id, 'toggle')}>{monitor.enabled ? 'Pause' : 'Resume'}</button></div></article>) : <p className="empty">No monitors yet. Connect an account, then add your number.</p>}</div></section>
    <section className="matches"><div className="section-title"><div><p className="eyebrow">RESULTS</p><h2>Matching emails and documents</h2></div><span>{matches.length} found</span></div>{matches.length ? <div className="table-wrap"><table><thead><tr><th>Email</th><th>Where found</th><th>Status</th><th>Received</th></tr></thead><tbody>{matches.map((match) => <tr key={match.id}><td><strong>{match.subject}</strong><span>{match.sender}</span></td><td><strong>{match.filename || 'Email'}</strong><span>{match.location}</span><small>{match.excerpt}</small></td><td>{match.status ? <b className="status">{match.status}</b> : '—'}</td><td>{match.received_at ? new Date(match.received_at).toLocaleString() : '—'}</td></tr>)}</tbody></table></div> : <p className="empty">Matches will appear here with the exact sheet/cell or document location.</p>}</section>
  </main>;
}
createRoot(document.getElementById('root')).render(<StrictMode><App /></StrictMode>);
