const GRAPH = 'https://graph.microsoft.com/v1.0';
const callbackUrl = () => `${process.env.API_URL || 'http://localhost:4100'}/api/auth/outlook/callback`;
async function tokenRequest(params) { const response = await fetch('https://login.microsoftonline.com/common/oauth2/v2.0/token', { method: 'POST', headers: { 'Content-Type': 'application/x-www-form-urlencoded' }, body: new URLSearchParams(params) }); if (!response.ok) throw new Error(`Microsoft token request failed: ${await response.text()}`); return response.json(); }
async function graph(accessToken, path) { const response = await fetch(`${GRAPH}${path}`, { headers: { Authorization: `Bearer ${accessToken}` } }); if (!response.ok) throw new Error(`Microsoft Graph request failed: ${await response.text()}`); return response.json(); }
export const outlookProvider = {
  authorizationUrl(state) { const url = new URL('https://login.microsoftonline.com/common/oauth2/v2.0/authorize'); url.search = new URLSearchParams({ client_id: process.env.MICROSOFT_CLIENT_ID, response_type: 'code', redirect_uri: callbackUrl(), response_mode: 'query', scope: 'offline_access Mail.Read', state }); return url.toString(); },
  async exchange(code) { const tokens = await tokenRequest({ client_id: process.env.MICROSOFT_CLIENT_ID, client_secret: process.env.MICROSOFT_CLIENT_SECRET, grant_type: 'authorization_code', code, redirect_uri: callbackUrl() }); return { ...tokens, expires_at: Date.now() + tokens.expires_in * 1000 }; },
  async refresh(tokens) { if (tokens.expires_at && tokens.expires_at > Date.now() + 60000) return tokens; const fresh = await tokenRequest({ client_id: process.env.MICROSOFT_CLIENT_ID, client_secret: process.env.MICROSOFT_CLIENT_SECRET, grant_type: 'refresh_token', refresh_token: tokens.refresh_token }); return { ...tokens, ...fresh, expires_at: Date.now() + fresh.expires_in * 1000 }; },
  async identity(tokens) { const profile = await graph(tokens.access_token, '/me?$select=mail,userPrincipalName'); return profile.mail || profile.userPrincipalName; },
  async listMessages(tokens, after) { const filter = after ? `&$filter=receivedDateTime ge ${encodeURIComponent(after)}` : ''; const result = await graph(tokens.access_token, `/me/mailFolders/inbox/messages?$top=50&$select=id,subject,from,receivedDateTime,body,hasAttachments${filter}`); return Promise.all(result.value.map((message) => this.getMessage(tokens, message.id))); },
  async getMessage(tokens, id) { const message = await graph(tokens.access_token, `/me/messages/${id}?$expand=attachments`); const attachments = (message.attachments || []).filter((item) => item['@odata.type'] === '#microsoft.graph.fileAttachment').map((item) => ({ filename: item.name, mimeType: item.contentType, content: Buffer.from(item.contentBytes, 'base64') })); return { id, subject: message.subject || '', from: message.from?.emailAddress?.address || '', receivedAt: message.receivedDateTime, body: message.body?.content || '', attachments }; },
};
